### ISSUE TITLE
Backend: go-audit events are not put into the streamstash index

### ISSUE THREAD

**Issue by pettai** [nbrownus/streamstash#11]
#### Description

Backend: streamstash wont put the go-audit events in the "streamstash" index

#### Reproducible in:

`go-audit` version: "master"
`streamstash` version: "master", as the suggested version in the example docs (`sudo npm install -g https://github.com/nbrownus/streamstash#2.0`) didn't work
OS version(s): Ubuntu 16.04 (on both backend & client)

#### Steps to reproduce:

1. Follow the example docs to install & configure
2. Start up everything

### Expected result:

According to the example docs a custom index should be created named "streamstash"
https://github.com/slackhq/go-audit/blob/master/examples/streamstash/streamstash.js#L21

### Actual result:

streamstash puts all events in the (default?) "logstash-*" index

**Comment by pettai** [comment]
Some more data points about the streamstash installation: 

ubuntu@streamstash:~$ sudo npm install -g https://github.com/nbrownus/streamstash#2.0
/usr/local/lib
└─┬ streamstash@1.3.0  (git+https://github.com/nbrownus/streamstash.git#3762c65be7a701b072f1b1e8402991a38d79397f)
  ├─┬ dashdash@1.13.0
  │ └── assert-plus@1.0.0
  ├── relp@0.5.2  (git://github.com/nbrownus/node-relp.git#51f9b4502578eaea87d5204f8ce93aa77c0877f0)
  ├── statsd-client@0.2.1
  ├── underscore@1.8.3
  └── uuid@3.0.1

ubuntu@streamstash:~$ sudo /usr/local/lib/node_modules/streamstash/bin/streamstash /etc/streamstash.js
/usr/local/lib/node_modules/streamstash/lib/outputs/ElasticSearchOutput.js:33
let ElasticSearchOutput = function (options) {
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/streamstash/lib/outputs/index.js:3:26)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)


ubuntu@streamstash:~$ sudo npm install -g https://github.com/nbrownus/streamstash
- uuid@3.0.1 node_modules/streamstash/node_modules/uuid
/usr/local/lib
└─┬ streamstash@1.3.0  (git+https://github.com/nbrownus/streamstash.git#bc80c9f6c0d867461f4f528a4ae4f3aeed01b7a9)
  ├─┬ dashdash@1.10.1
  │ └── assert-plus@0.1.5
  └── relp@0.5.0

ubuntu@streamstash:~$ sudo /usr/local/lib/node_modules/streamstash/bin/streamstash /etc/streamstash.js
[2018-08-28T08:07:39.133Z] INFO Starting!
[2018-08-28T08:07:39.135Z] INFO RELP started
[2018-08-28T08:07:39.136Z] INFO ElasticSearch started
^C[2018-08-28T08:07:41.033Z] INFO Got SIGINT, starting shutdown
[2018-08-28T08:07:41.035Z] INFO Forceful exit in 30 seconds
[2018-08-28T08:07:41.036Z] INFO Telling all input plugins to stop emitting
[2018-08-28T08:07:41.037Z] INFO All input plugins have stopped emitting
[2018-08-28T08:07:41.037Z] INFO Waiting for 0 in flight events to complete
[2018-08-28T08:07:41.037Z] INFO All in flight events have completed
[2018-08-28T08:07:41.037Z] INFO Stopping all 2 plugins
[2018-08-28T08:07:41.038Z] INFO All plugins have completely stopped
[2018-08-28T08:07:41.039Z] INFO Exited gracefully

**Comment by pettai** [comment]
This looks like several issues:
* "the current issue" streamstash-master doesn't put go-audit events in the streamstash index
* streamstash#2.0 doesn't work with the suggested nodejs installation instructions from go-audit
   examples docs.
   - outdated example docs in go-audit (https://github.com/slackhq/go-audit/tree/master/examples/streamstash)?
   - problem with the streamstash#2.0 branch ?

**Comment by pettai** [comment]
Ok, backing back to an older commit from the 2.0 branch solves the problem, so it seems to be related to the current latest version of 2.0

**Comment by nbrownus** [comment]
Looks like there are 2 issues here. 

1. Your version of `node` doesn't fully support the es6 features being used here, is it possible for you to upgrade `node`?
2. I certainly broke custom index naming, will fix shortly.
